import { MenuCategory, MenuItem } from '@/types';

export const categories: MenuCategory[] = [
  { id: 'local',       name: 'Local',            sortOrder: 1 },
  { id: 'continental', name: 'Continental',       sortOrder: 2 },
  { id: 'snacks',      name: 'Snacks & Wraps',   sortOrder: 3 },
  { id: 'junk',        name: 'Junk & Fast Food', sortOrder: 4 },
  { id: 'desserts',    name: 'Desserts',          sortOrder: 5 },
  { id: 'drinks',      name: 'Drinks',            sortOrder: 6 },
];

const img = (base: string) => `${base}?w=600&h=400&q=80&auto=format&fit=crop`;

export const menuItems: MenuItem[] = [
  // ── LOCAL ──────────────────────────────────────────────────────────────────
  {
    id: 'l1',
    categoryId: 'local',
    name: 'Jollof Rice',
    description: 'Party-style jollof rice slow-cooked over firewood, served with grilled chicken and fried plantain.',
    price: 4500,
    isAvailable: true,
    rating: 5.0,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1694141252132-2555bae46f50'),
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'l2',
    categoryId: 'local',
    name: 'Egusi Soup + Eba',
    description: 'Ground melon seed soup with bitter leaf, assorted meat and stockfish. Served with freshly made eba.',
    price: 5500,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://images.unsplash.com/photo-1763048443535-1243379234e2'),
    allergens: ['fish'],
  },
  {
    id: 'l3',
    categoryId: 'local',
    name: 'Afang Soup',
    description: 'Efik soup with afang leaves, waterleaf, assorted meat and periwinkle. Served with garri.',
    price: 5800,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1711915408847-ae32b80a3fd0'),
    allergens: ['shellfish', 'fish'],
  },
  {
    id: 'l4',
    categoryId: 'local',
    name: 'Ofada Rice & Ayamase',
    description: 'Local brown ofada rice served with designer ayamase stew and assorted meat.',
    price: 4800,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1665332195309-9d75071138f0'),
  },
  {
    id: 'l5',
    categoryId: 'local',
    name: 'Banga Soup + Starch',
    description: 'Delta-style palm nut soup with oburunbebe stick, native spices and catfish. Served with starch.',
    price: 5200,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1756201408993-3b0f802d2677'),
    allergens: ['fish'],
  },
  {
    id: 'l6',
    categoryId: 'local',
    name: 'Ofe Onugbu + Fufu',
    description: 'Igbo bitter leaf soup slow-cooked with assorted meats. Served with pounded yam fufu.',
    price: 5000,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1723579374186-cca58e8672d7'),
  },
  {
    id: 'l7',
    categoryId: 'local',
    name: 'Suya Platter',
    description: 'Grilled beef suya seasoned with yaji and groundnut, served with onions, tomatoes and coleslaw.',
    price: 3500,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://images.unsplash.com/photo-1633436375795-12b3b339712f'),
    allergens: ['groundnut'],
  },
  {
    id: 'l8',
    categoryId: 'local',
    name: 'Catfish Pepper Soup',
    description: 'Fiery catfish pepper soup with utazi leaves and our signature spice blend.',
    price: 3500,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1625944228691-997b74fa5866'),
    allergens: ['fish'],
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'l9',
    categoryId: 'local',
    name: 'Fried Rice & Chicken',
    description: 'Nigerian-style fried rice with vegetables, liver and grilled chicken. A celebration staple.',
    price: 4500,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1664992960082-0ea299a9c53e'),
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'l10',
    categoryId: 'local',
    name: 'Oha Soup + Pounded Yam',
    description: 'Creamy oha leaf soup with cocoyam thickener and assorted Igbo meats. Served with pounded yam.',
    price: 5500,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1711915408337-ae6b1207e42d'),
  },

  // ── CONTINENTAL ────────────────────────────────────────────────────────────
  {
    id: 'c1',
    categoryId: 'continental',
    name: 'Spaghetti Bolognese',
    description: 'Al dente spaghetti with slow-cooked beef and tomato ragù, topped with parmesan.',
    price: 4200,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1473093295043-cdd812d0e601'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'c2',
    categoryId: 'continental',
    name: 'Grilled Salmon',
    description: 'Atlantic salmon fillet, herb-crusted, served with roasted potatoes and green beans.',
    price: 7500,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1723575688671-fc98e2f3fcae'),
    allergens: ['fish'],
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'c3',
    categoryId: 'continental',
    name: 'BBQ Beef Ribs',
    description: 'Slow-smoked beef ribs in smoky BBQ sauce, served with coleslaw and fries.',
    price: 8500,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://images.unsplash.com/photo-1558030137-a56c1b004fa3'),
    allergens: ['gluten'],
  },
  {
    id: 'c4',
    categoryId: 'continental',
    name: 'Creamy Pasta Alfredo',
    description: 'Fettuccine in a rich Parmesan cream sauce with grilled chicken and roasted garlic.',
    price: 4500,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1611270629569-8b357cb88da9'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'c5',
    categoryId: 'continental',
    name: 'Grilled Chicken Steak',
    description: 'Marinated chicken breast steak served with mashed potatoes, sautéed mushrooms and peppercorn sauce.',
    price: 5500,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1664478272084-532c1bfebd25'),
    allergens: ['dairy'],
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'c6',
    categoryId: 'continental',
    name: 'Prawn Stir-Fry',
    description: 'Tiger prawns wok-tossed with bell peppers, ginger, garlic and oyster sauce. Served with jasmine rice.',
    price: 6500,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1695882257873-4a4ad25b8c7c'),
    allergens: ['shellfish', 'gluten'],
  },
  {
    id: 'c7',
    categoryId: 'continental',
    name: 'Caesar Salad',
    description: 'Crispy romaine, shaved parmesan, croutons and house-made Caesar dressing. Add grilled chicken +₦800.',
    price: 3200,
    isAvailable: true,
    rating: 4.5,
    imageUrl: img('https://images.unsplash.com/photo-1546549032-9571cd6b27df'),
    allergens: ['gluten', 'dairy', 'fish'],
  },
  {
    id: 'c8',
    categoryId: 'continental',
    name: 'Beef Lasagne',
    description: 'Layered pasta sheets with beef mince, béchamel and tomato ragù, baked golden.',
    price: 5000,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1600803907087-f56d462fd26b'),
    allergens: ['gluten', 'dairy'],
  },

  // ── SNACKS & WRAPS ─────────────────────────────────────────────────────────
  {
    id: 's1',
    categoryId: 'snacks',
    name: 'Chicken Shawarma',
    description: 'Grilled seasoned chicken, coleslaw, pickled veggies and garlic sauce rolled in a soft tortilla.',
    price: 2500,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1700677185953-f9473e7e2ba1'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 's2',
    categoryId: 'snacks',
    name: 'Beef Wrap',
    description: 'Spiced minced beef, diced tomatoes, onions and pepper sauce wrapped in a grilled flatbread.',
    price: 2200,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1529006557810-274b9b2fc783'),
    allergens: ['gluten'],
  },
  {
    id: 's3',
    categoryId: 'snacks',
    name: 'Spring Rolls (4 pcs)',
    description: 'Crispy fried rolls stuffed with mixed vegetables, glass noodles and ginger. Served with sweet chilli.',
    price: 1800,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1589301773859-bb024d3ad558'),
    allergens: ['gluten'],
    dietaryTags: ['vegan'],
  },
  {
    id: 's4',
    categoryId: 'snacks',
    name: 'Puff-Puff',
    description: 'Light and airy deep-fried dough balls, lightly sweetened. Six pieces.',
    price: 1200,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1663854478810-26b620ade38a'),
    dietaryTags: ['vegan'],
  },
  {
    id: 's5',
    categoryId: 'snacks',
    name: 'Samosa (3 pcs)',
    description: 'Crispy pastry triangles filled with spiced beef and potatoes. Served with mango chutney.',
    price: 1500,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1697155836252-d7f969108b5a'),
    allergens: ['gluten'],
  },
  {
    id: 's6',
    categoryId: 'snacks',
    name: 'Chicken Wrap',
    description: 'Grilled chicken strips, lettuce, tomato and honey mustard wrapped in a wholemeal tortilla.',
    price: 2200,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1681072530653-db8fe2538631'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 's7',
    categoryId: 'snacks',
    name: 'Meat Pie',
    description: 'Nigerian-style shortcrust pastry filled with seasoned minced beef, potatoes and carrots.',
    price: 800,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1695297516676-04a259917c03'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 's8',
    categoryId: 'snacks',
    name: 'Gizdodo',
    description: 'Gizzard and fried plantain stir-fried with bell peppers and onions in palm oil sauce.',
    price: 2800,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1762884601729-0eeeafbdfb8a'),
    dietaryTags: ['gluten-free'],
  },

  // ── JUNK & FAST FOOD ───────────────────────────────────────────────────────
  {
    id: 'j1',
    categoryId: 'junk',
    name: 'Classic Cheeseburger',
    description: 'Smash-style beef patty, cheddar, pickles, caramelised onions and house sauce in a brioche bun.',
    price: 3500,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1683619761468-b06992704398'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'j2',
    categoryId: 'junk',
    name: 'Crispy Fried Chicken',
    description: 'Bone-in chicken pieces in a seasoned crispy buttermilk batter. Served with fries and coleslaw.',
    price: 4000,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1683139916670-38113db90cb9'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'j3',
    categoryId: 'junk',
    name: 'Loaded Fries',
    description: 'Thick-cut fries topped with melted cheddar, crispy bacon bits, jalapeños and sour cream.',
    price: 2500,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1639339269792-740cd03f0ac9'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'j4',
    categoryId: 'junk',
    name: 'Pepperoni Pizza',
    description: '10-inch hand-stretched pizza with tomato sauce, mozzarella and pepperoni.',
    price: 5500,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1547754070-c73f90c116b5'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'j5',
    categoryId: 'junk',
    name: 'Chicken Wings (6 pcs)',
    description: 'Crispy chicken wings tossed in your choice of Buffalo, BBQ or suya dry rub sauce.',
    price: 3200,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1586793783658-261cddf883ef'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'j6',
    categoryId: 'junk',
    name: 'Double Beef Burger',
    description: 'Two smash patties, double cheddar, lettuce, tomato, red onion and special burger sauce.',
    price: 4500,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://images.unsplash.com/photo-1662186342592-5b1236e95a4e'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'j7',
    categoryId: 'junk',
    name: 'Hotdog',
    description: 'Jumbo beef frank in a toasted brioche bun with mustard, ketchup and fried onions.',
    price: 2200,
    isAvailable: true,
    rating: 4.5,
    imageUrl: img('https://images.unsplash.com/photo-1603614550145-c7bb90bbfddf'),
    allergens: ['gluten'],
  },
  {
    id: 'j8',
    categoryId: 'junk',
    name: 'Chicken Sandwich',
    description: 'Crispy fried chicken thigh, pickles, shredded cabbage and spicy mayo in a toasted potato bun.',
    price: 3000,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1600555379765-f82335a7b1b0'),
    allergens: ['gluten', 'dairy'],
  },

  // ── DESSERTS ───────────────────────────────────────────────────────────────
  {
    id: 'd1',
    categoryId: 'desserts',
    name: 'Chocolate Lava Cake',
    description: 'Warm dark chocolate fondant with a molten centre. Served with vanilla ice cream.',
    price: 2500,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1715015440855-7d95cf92608a'),
    allergens: ['gluten', 'dairy', 'egg'],
  },
  {
    id: 'd2',
    categoryId: 'desserts',
    name: 'Coconut Candy',
    description: 'Freshly made Nigerian coconut candy with palm sugar. Sweet, chewy and traditional.',
    price: 700,
    isAvailable: true,
    rating: 4.4,
    imageUrl: img('https://images.unsplash.com/photo-1762941904142-9d91ca413e66'),
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    id: 'd3',
    categoryId: 'desserts',
    name: 'Boli & Groundnut',
    description: 'Roasted plantain with spiced groundnut — a timeless street-food pairing.',
    price: 1500,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1540714605746-4f474eefc6d4'),
    allergens: ['groundnut'],
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    id: 'd4',
    categoryId: 'desserts',
    name: 'Cheesecake Slice',
    description: 'New York-style baked cheesecake with a buttery biscuit base and berry compote.',
    price: 2200,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1667546202654-e7574a20872c'),
    allergens: ['gluten', 'dairy', 'egg'],
  },
  {
    id: 'd5',
    categoryId: 'desserts',
    name: 'Ice Cream (2 scoops)',
    description: 'Choice of vanilla, chocolate or strawberry. Served with waffle cone pieces.',
    price: 1500,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1708175313814-679cb8e90d2e'),
    allergens: ['dairy'],
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'd6',
    categoryId: 'desserts',
    name: 'Puff-Puff & Honey',
    description: 'Classic puff-puff drizzled with wildflower honey and a dusting of cinnamon.',
    price: 1400,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1683531731340-ff35378582a4'),
    dietaryTags: ['vegan'],
  },
  {
    id: 'd7',
    categoryId: 'desserts',
    name: 'Sweet Chin-Chin',
    description: 'Crunchy fried dough with powdered sugar. 200g pack, made fresh daily.',
    price: 1200,
    isAvailable: true,
    rating: 4.5,
    imageUrl: img('https://images.unsplash.com/photo-1517427294546-5aa121f68e8a'),
    dietaryTags: ['vegan'],
  },
  {
    id: 'd8',
    categoryId: 'desserts',
    name: 'Fura da Nono',
    description: 'Fermented milk with millet balls. A Fulani classic — cool, thick and tangy.',
    price: 900,
    isAvailable: true,
    rating: 4.5,
    imageUrl: img('https://images.unsplash.com/photo-1718985344972-d0eaf1ba5d72'),
    allergens: ['dairy'],
    dietaryTags: ['gluten-free'],
  },

  // ── DRINKS ─────────────────────────────────────────────────────────────────
  {
    id: 'dr1',
    categoryId: 'drinks',
    name: 'Chapman',
    description: 'Nigerian cocktail with Fanta, Sprite, grenadine, cucumber and Angostura bitters.',
    price: 1500,
    isAvailable: true,
    rating: 4.8,
    imageUrl: img('https://images.unsplash.com/photo-1551024709-8f23befc6f87'),
    dietaryTags: ['vegan'],
  },
  {
    id: 'dr2',
    categoryId: 'drinks',
    name: 'Zobo',
    description: 'Hibiscus flower drink with ginger, pineapple and cloves. Chilled and refreshing.',
    price: 800,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1600271886742-f049cd451bba'),
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    id: 'dr3',
    categoryId: 'drinks',
    name: 'Kunu Aya',
    description: 'Tiger nut milk with dates and coconut. Naturally sweet and energising.',
    price: 1000,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://images.unsplash.com/photo-1600718374662-0483d2b9da44'),
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    id: 'dr4',
    categoryId: 'drinks',
    name: 'Fresh Coconut Water',
    description: 'Chilled straight from the coconut. Nothing added, nothing removed.',
    price: 700,
    isAvailable: true,
    rating: 4.9,
    imageUrl: img('https://images.unsplash.com/photo-1496318447583-f524534e9ce1'),
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    id: 'dr5',
    categoryId: 'drinks',
    name: 'Smoothie Bowl',
    description: 'Blended mango, banana and pineapple topped with granola, coconut flakes and honey.',
    price: 2000,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1663091544172-794c537af00c'),
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'dr6',
    categoryId: 'drinks',
    name: 'Milkshake',
    description: 'Thick creamy milkshake — chocolate, vanilla or strawberry. Topped with whipped cream.',
    price: 1800,
    isAvailable: true,
    rating: 4.7,
    imageUrl: img('https://images.unsplash.com/photo-1622597467836-f3285f2131b8'),
    allergens: ['dairy'],
    dietaryTags: ['gluten-free'],
  },
  {
    id: 'dr7',
    categoryId: 'drinks',
    name: 'Tsamiya Juice',
    description: 'Sweet-sour tamarind drink with ginger and a touch of pepper.',
    price: 900,
    isAvailable: true,
    rating: 4.5,
    imageUrl: img('https://images.unsplash.com/photo-1598994392980-53a7fb033bcc'),
    dietaryTags: ['vegan', 'gluten-free'],
  },
  {
    id: 'dr8',
    categoryId: 'drinks',
    name: 'Zobo Soda',
    description: 'Our house zobo blend, lightly carbonated with a squeeze of lime.',
    price: 1000,
    isAvailable: true,
    rating: 4.6,
    imageUrl: img('https://plus.unsplash.com/premium_photo-1684952849219-5a0d76012ed2'),
    dietaryTags: ['vegan', 'gluten-free'],
  },
];

export function getItemsByCategory(categoryId: string): MenuItem[] {
  return menuItems.filter((item) => item.categoryId === categoryId);
}

export function getTopPicks(): MenuItem[] {
  return menuItems
    .filter((item) => item.rating && item.rating >= 4.8)
    .sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0))
    .slice(0, 6);
}
